version: "3"

services:
  service:
    build: .
    env_file:
      - .env
    expose:
      - '3000'
    depends_on:
      - db
    environment:
      - PRODUCTION=1
    restart: 'on-failure:5'
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        tag: "{{.Name}}"

  db:
    image: postgres:latest
    expose:
      - '5432'
    env_file:
      - .env
    restart: 'always'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
